import Link from 'next/link'
import { ArrowLeft, ArrowRight, Wand2 } from 'lucide-react'
import { getAllWireframeDatasets } from '@/lib/wireframe-datasets'
import { getColorClasses, getDatasetIcon, type ColorToken } from '@/lib/datasets'
import { Section } from '../_components/Section'

export const metadata = {
  title: 'Wireframe gallery',
  description:
    'Six dataset-driven wireframes across manufacturing, real estate, healthcare, education, SaaS, and logistics. Each layout is generated from the dataset schema + a hand-curated profiling fixture. Switch between Sparse, Balanced, and Dense density modes inside any wireframe.',
}

export default function WireframeGalleryPage() {
  const datasets = getAllWireframeDatasets()

  return (
    <>
      {/* Back link */}
      <div className="section-container pt-8">
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-sm text-text-muted hover:text-accent transition-colors"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to home
        </Link>
      </div>

      <Section
        eyebrow="For Developers · Discovery mode"
        title="Six dataset-driven wireframes"
        description="Each layout is generated by the wireframe engine from a dataset schema + a profiling fixture. Switch between Sparse, Balanced, and Dense density modes inside any wireframe to see the same data presented for executives, exploratory analysts, and operational dashboards."
      >
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {datasets.map((dataset) => {
            const Icon = getDatasetIcon(dataset.metadata.icon)
            const colors = getColorClasses(dataset.metadata.colorToken as ColorToken)
            return (
              <Link
                key={dataset.id}
                href={`/wireframe/${dataset.id}`}
                className="group rounded-xl border border-surface-border bg-surface overflow-hidden transition-all hover:border-accent/40 hover:shadow-card-hover hover:-translate-y-0.5"
              >
                {/* Thumbnail */}
                <div
                  className={`relative aspect-[16/10] ${colors.thumbBg} border-b ${colors.thumbBorder} flex items-center justify-center overflow-hidden`}
                >
                  <Icon
                    className={`h-12 w-12 ${colors.iconColor} relative z-10`}
                    strokeWidth={1.5}
                  />
                  <div className="absolute inset-0 dot-pattern opacity-30" aria-hidden="true" />
                </div>

                {/* Body */}
                <div className="p-5">
                  <div className="flex items-center justify-between mb-3">
                    <span
                      className={`inline-flex items-center font-mono text-[10px] uppercase tracking-widest px-2 py-1 rounded border ${colors.badgeBg} ${colors.badgeText} ${colors.badgeBorder}`}
                    >
                      {dataset.metadata.domain}
                    </span>
                    <span className="font-mono text-xs text-text-muted">
                      {dataset.metadata.rowCount} rows
                    </span>
                  </div>
                  <h3 className="font-display text-lg font-semibold tracking-tight mb-1 group-hover:text-accent transition-colors">
                    {dataset.metadata.title}
                  </h3>
                  <p className="text-sm text-text-muted leading-relaxed line-clamp-2">
                    {dataset.metadata.tagline}
                  </p>
                  <div className="mt-4 inline-flex items-center gap-1.5 text-sm font-medium text-accent group-hover:gap-2.5 transition-all">
                    <Wand2 className="h-3.5 w-3.5" />
                    Open wireframe
                    <ArrowRight className="h-4 w-4" />
                  </div>
                </div>
              </Link>
            )
          })}
        </div>

        <p className="mt-12 max-w-2xl text-sm text-text-muted leading-relaxed">
          These wireframes are generated, not hand-coded. The engine reads the schema and the
          profiling fixture, picks the appropriate chart types (bar, line, donut, heatmap,
          scatter, funnel, histogram), and lays them out in one of three density modes. Same
          engine that powers the ad-hoc dashboard, just driven by curated profiling instead of
          live filter state.
        </p>
      </Section>
    </>
  )
}
